"""Run this project end to end, and write down that it ran.

A repository whose continuous integration is frozen says nothing about itself: the green tick
is two years old, or absent. What replaces it is ``reports/run-evidence.json`` — the exact
command, the day, the revision, the tool versions, what it cost, and the tracked files it
produced. A reader can rerun that command and compare.

**The run must reproduce what the repository publishes.** The steps below regenerate the key
outputs; if any of them comes out different from the committed version, no evidence is
written and the differing files are named. That is the whole value of the exercise: evidence
that merely says « it ran » proves that something ran, not that what is published is what it
produces.

    cd backend && uv run python scripts/smoke.py

Run it on a clean clone, before the release tag. No workflow writes this file: a committed
artefact regenerated by continuous integration is an artefact whose author is a machine
nobody watches.

**Two of the four published tables are replayable here, and two are not.** The retrieval
ablation needs Milvus holding an ingested corpus, and the latency bench needs the six
containers; both are named in `docs/protocol.md` with the command that produces them. What
this run covers is everything that replays from a committed file: the threshold sweep, the
re-judgement of the saved model answers, and one full pass of the agent with every external
service unreachable.
"""

from __future__ import annotations

import json
import os
import platform
import shutil
import subprocess
import sys
import time
from datetime import UTC, datetime
from importlib.metadata import PackageNotFoundError, version

from chess_coach.utils.paths import ROOT_DIR

#: `key_output` is read from the checkout, not from the project, so the paths below are
#: written the way a reader at the top of the repository sees them.
REPO_DIR = ROOT_DIR.parent

EVIDENCE = "reports/run-evidence.json"
COMMAND = "cd backend && uv run python scripts/smoke.py"

#: What this run has to regenerate byte for byte before any evidence is written. Two
#: published tables that replay from a committed file, each beside the JSON or CSV it is
#: rendered from.
KEY_OUTPUT: tuple[str, ...] = (
    "backend/reports/theory_threshold_sweep.csv",
    "backend/reports/theory_threshold_sweep.md",
    "backend/reports/move_invention.json",
    "backend/reports/move_invention.md",
)

#: The distributions whose version changes the result. Not the whole lock file — the reader
#: needs what would explain a different number, not an inventory.
TOOLS: tuple[str, ...] = ("chess", "langgraph", "pydantic", "fastapi", "pymilvus")

#: The Ruy Lopez after 3.Bb5, which is the position the README shows.
POSITION = "r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3"


def _run(*arguments: str) -> None:
    """Launch one script of `scripts/` as a child, and give up on a non-zero exit.

    Whatever it printed is printed here too, success or failure. Somebody rerunning this by
    hand types the same command and sees the same lines; a run that swallowed them would make
    the two accounts disagree.
    """
    print(f"$ python {' '.join(arguments)}")
    done = subprocess.run(
        [sys.executable, *arguments],
        cwd=str(ROOT_DIR),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        # The reports carry accented French. A child left to the Windows console encoding
        # writes bytes this process cannot decode, and the smoke run dies printing the output
        # of a step that succeeded.
        env={**os.environ, "PYTHONIOENCODING": "utf-8"},
    )
    print(done.stdout, end="")
    if done.returncode != 0:
        print(done.stderr, end="", file=sys.stderr)
        raise SystemExit(f"{' '.join(arguments)} exited with {done.returncode}")


def answer_one_position() -> None:
    """Put a position to the agent with nothing behind it, and check what comes back.

    This is the part a reader of the README is promised: the product works with no key and no
    container. The graph runs its four nodes, each source fails to reach anything, and the
    answer is built from the local opening book and the deterministic template.
    """
    from chess_coach.agent.graph import build_default_agent

    unreachable = {
        "MILVUS_HOST": "127.0.0.1",
        "MILVUS_PORT": "1",
        "MONGODB_URI": "mongodb://127.0.0.1:1",
        "LICHESS_TOKEN": "",
        "YOUTUBE_API_KEY": "",
        "LLM_ENABLED": "false",
    }
    for name, value in unreachable.items():
        os.environ[name] = value

    state = build_default_agent().run(POSITION)

    if not state.get("valid"):
        raise SystemExit("the agent refused a legal position")
    if not state.get("opening_name"):
        raise SystemExit("the local opening book named no opening for the Ruy Lopez")
    if not state.get("recommendation"):
        raise SystemExit("no recommendation was written with the model disabled")
    print(
        f"  agent: {state['opening_name']} ({state.get('opening_eco')}), "
        f"sources {state.get('sources_used')}"
    )


def steps() -> None:
    """What the product does, end to end, written as the README says to run it."""
    print("[1/3] one position through the agent, every service unreachable")
    answer_one_position()

    print("[2/3] the routing sweep, replayed on the frozen Explorer reading")
    _run("-m", "scripts.sweep_theory_threshold")

    print("[3/3] the saved model answers, judged again by the current reader")
    _run("-m", "scripts.check_move_invention", "--rejudge")


# --- What the evidence records ----------------------------------------------


def _git(*arguments: str) -> str:
    done = subprocess.run(
        ["git", *arguments], cwd=REPO_DIR, capture_output=True, text=True, check=False
    )
    return done.stdout.strip()


def tool_versions() -> dict[str, str]:
    versions = {"python": platform.python_version()}
    for name in TOOLS:
        try:
            versions[name] = version(name)
        except PackageNotFoundError:
            versions[name] = "not installed"
    for binary, arguments in (("uv", ("--version",)), ("docker", ("--version",))):
        if shutil.which(binary):
            done = subprocess.run([binary, *arguments], capture_output=True, text=True, check=False)
            versions[binary] = done.stdout.strip() or "unknown"
    return versions


def reproduced() -> list[str]:
    """The key outputs the run did NOT reproduce: missing, untracked, or changed."""
    problems: list[str] = []
    for rel in KEY_OUTPUT:
        if not (REPO_DIR / rel).exists():
            problems.append(f"{rel} — not produced")
            continue
        if not _git("ls-files", "--error-unmatch", rel):
            problems.append(f"{rel} — produced but not tracked by git")
            continue
        if _git("status", "--porcelain", "--", rel):
            problems.append(f"{rel} — differs from the committed version")
    return problems


def main() -> int:
    # Same reason as the child's encoding, on this side of the pipe.
    for stream in (sys.stdout, sys.stderr):
        stream.reconfigure(encoding="utf-8", errors="replace")

    started = time.monotonic()
    steps()
    duration = round(time.monotonic() - started, 1)

    differences = reproduced()
    if differences:
        print("the run did not reproduce what is published:", file=sys.stderr)
        for line in differences:
            print(f"  {line}", file=sys.stderr)
        print(f"{EVIDENCE} not written", file=sys.stderr)
        return 1

    evidence = {
        "command": COMMAND,
        "ran_at": datetime.now(tz=UTC).date().isoformat(),
        "git_revision": _git("rev-parse", "HEAD"),
        "tool_versions": tool_versions(),
        "duration_seconds": duration,
        "key_output": list(KEY_OUTPUT),
        # Null, and said so: the workflows of this repository lint, scan and test, and none
        # of them produces the evidence. A missing key would read as an oversight.
        "workflow_run_url": None,
    }
    target = ROOT_DIR / EVIDENCE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(evidence, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline=""
    )
    print(f"{EVIDENCE} written — {duration}s, {len(KEY_OUTPUT)} output(s) reproduced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
